config/routes.rb
Rails.application.routes.draw do
  resources :viewings

  resources :holidays

  resources :operatinghours

  resources :newstypes

  resources :news_items

  resources :roles

  resources :newsitems

  resources :staffs

end

app/models/viewing.rb
class Viewing < ActiveRecord::Base
end

app/controllers/viewings_controller.rb
class ViewingsController < ApplicationController
  before_action :set_viewing, only: [:show, :edit, :update, :destroy]

  # GET /viewings
  # GET /viewings.json
  def index
    @viewings = Viewing.all
  end

  # GET /viewings/1
  # GET /viewings/1.json
  def show
  end

  # GET /viewings/new
  def new
    @viewing = Viewing.new
  end

  # GET /viewings/1/edit
  def edit
  end

  # POST /viewings
  # POST /viewings.json
  def create
    @viewing = Viewing.new(viewing_params)

    respond_to do |format|
      if @viewing.save
        format.html { redirect_to @viewing, notice: 'Viewing was successfully created.' }
        format.json { render :show, status: :created, location: @viewing }
      else
        format.html { render :new }
        format.json { render json: @viewing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /viewings/1
  # PATCH/PUT /viewings/1.json
  def update
    respond_to do |format|
      if @viewing.update(viewing_params)
        format.html { redirect_to @viewing, notice: 'Viewing was successfully updated.' }
        format.json { render :show, status: :ok, location: @viewing }
      else
        format.html { render :edit }
        format.json { render json: @viewing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /viewings/1
  # DELETE /viewings/1.json
  def destroy
    @viewing.destroy
    respond_to do |format|
      format.html { redirect_to viewings_url, notice: 'Viewing was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_viewing
      @viewing = Viewing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def viewing_params
      params.require(:viewing).permit(:newsitem_id, :time)
    end
end

app/helpers/viewings_helper.rb
module ViewingsHelper
end

app/views/viewings/_form.html.erb
<%= form_for(@viewing) do |f| %>
  <% if @viewing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@viewing.errors.count, "error") %> prohibited this viewing from being saved:</h2>

      <ul>
      <% @viewing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :newsitem_id %><br>
    <%= f.number_field :newsitem_id %>
  </div>
  <div class="field">
    <%= f.label :time %><br>
    <%= f.datetime_select :time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/viewings/edit.html.erb
<h1>Editing viewing</h1>

<%= render 'form' %>

<%= link_to 'Show', @viewing %> |
<%= link_to 'Back', viewings_path %>

app/views/viewings/index.html.erb
<h1>Listing viewings</h1>

<table>
  <thead>
    <tr>
      <th>Newsitem</th>
      <th>Time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @viewings.each do |viewing| %>
      <tr>
        <td><%= viewing.newsitem_id %></td>
        <td><%= viewing.time %></td>
        <td><%= link_to 'Show', viewing %></td>
        <td><%= link_to 'Edit', edit_viewing_path(viewing) %></td>
        <td><%= link_to 'Destroy', viewing, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Viewing', new_viewing_path %>

app/views/viewings/new.html.erb
<h1>New viewing</h1>

<%= render 'form' %>

<%= link_to 'Back', viewings_path %>

app/views/viewings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Newsitem:</strong>
  <%= @viewing.newsitem_id %>
</p>

<p>
  <strong>Time:</strong>
  <%= @viewing.time %>
</p>

<%= link_to 'Edit', edit_viewing_path(@viewing) %> |
<%= link_to 'Back', viewings_path %>