config/routes.rb
Rails.application.routes.draw do
  resources :viewings

  resources :holidays

  resources :operatinghours

  resources :newstypes

  resources :news_items

  resources :roles

  resources :newsitems

  resources :staffs

end

app/controllers/newstypes_controller.rb
class NewstypesController < ApplicationController
  before_action :set_newstype, only: [:show, :edit, :update, :destroy]

  # GET /newstypes
  # GET /newstypes.json
  def index
    @newstypes = Newstype.all
  end

  # GET /newstypes/1
  # GET /newstypes/1.json
  def show
  end

  # GET /newstypes/new
  def new
    @newstype = Newstype.new
  end

  # GET /newstypes/1/edit
  def edit
  end

  # POST /newstypes
  # POST /newstypes.json
  def create
    @newstype = Newstype.new(newstype_params)

    respond_to do |format|
      if @newstype.save
        format.html { redirect_to @newstype, notice: 'Newstype was successfully created.' }
        format.json { render :show, status: :created, location: @newstype }
      else
        format.html { render :new }
        format.json { render json: @newstype.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /newstypes/1
  # PATCH/PUT /newstypes/1.json
  def update
    respond_to do |format|
      if @newstype.update(newstype_params)
        format.html { redirect_to @newstype, notice: 'Newstype was successfully updated.' }
        format.json { render :show, status: :ok, location: @newstype }
      else
        format.html { render :edit }
        format.json { render json: @newstype.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /newstypes/1
  # DELETE /newstypes/1.json
  def destroy
    @newstype.destroy
    respond_to do |format|
      format.html { redirect_to newstypes_url, notice: 'Newstype was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_newstype
      @newstype = Newstype.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def newstype_params
      params.require(:newstype).permit(:extension, :viewer, :jscript, :pretags, :posttags)
    end
end

app/helpers/newstypes_helper.rb
module NewstypesHelper
end

app/views/newstypes/_form.html.erb
<%= form_for(@newstype) do |f| %>
  <% if @newstype.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@newstype.errors.count, "error") %> prohibited this newstype from being saved:</h2>

      <ul>
      <% @newstype.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :extension %><br>
    <%= f.text_field :extension %>
  </div>
  <div class="field">
    <%= f.label :viewer %><br>
    <%= f.text_field :viewer %>
  </div>
  <div class="field">
    <%= f.label :jscript %><br>
    <%= f.text_field :jscript %>
  </div>
  <div class="field">
    <%= f.label :pretags %><br>
    <%= f.text_field :pretags %>
  </div>
  <div class="field">
    <%= f.label :posttags %><br>
    <%= f.text_field :posttags %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/newstypes/edit.html.erb
<h1>Editing newstype</h1>

<%= render 'form' %>

<%= link_to 'Show', @newstype %> |
<%= link_to 'Back', newstypes_path %>

app/views/newstypes/index.html.erb
<h1>Listing newstypes</h1>

<table>
  <thead>
    <tr>
      <th>Extension</th>
      <th>Viewer</th>
      <th>Jscript</th>
      <th>Pretags</th>
      <th>Posttags</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @newstypes.each do |newstype| %>
      <tr>
        <td><%= newstype.extension %></td>
        <td><%= newstype.viewer %></td>
        <td><%= newstype.jscript %></td>
        <td><%= newstype.pretags %></td>
        <td><%= newstype.posttags %></td>
        <td><%= link_to 'Show', newstype %></td>
        <td><%= link_to 'Edit', edit_newstype_path(newstype) %></td>
        <td><%= link_to 'Destroy', newstype, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Newstype', new_newstype_path %>

app/views/newstypes/new.html.erb
<h1>New newstype</h1>

<%= render 'form' %>

<%= link_to 'Back', newstypes_path %>

app/views/newstypes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Extension:</strong>
  <%= @newstype.extension %>
</p>

<p>
  <strong>Viewer:</strong>
  <%= @newstype.viewer %>
</p>

<p>
  <strong>Jscript:</strong>
  <%= @newstype.jscript %>
</p>

<p>
  <strong>Pretags:</strong>
  <%= @newstype.pretags %>
</p>

<p>
  <strong>Posttags:</strong>
  <%= @newstype.posttags %>
</p>

<%= link_to 'Edit', edit_newstype_path(@newstype) %> |
<%= link_to 'Back', newstypes_path %>